(function(){
  'use strict';
  const cfg=window.RICREATIONS_SUPABASE||{};
  const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(cfg.url||'')&&!String(cfg.publishableKey||'').startsWith('YOUR_');
  const client=configured&&window.supabase?.createClient?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
  const $=(selector)=>document.querySelector(selector); const $$=(selector)=>[...document.querySelectorAll(selector)];
  const form=$('#contentForm'); let items=[];let filter='all';let search='';let session=null;let activeId='';let dirty=false;let saveTimer=null;
  const status=(element,message,error=false)=>{element.textContent=message;element.classList.toggle('is-error',error)};
  const escapeText=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const slugify=(value)=>String(value||'').toLowerCase().trim().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const isAdmin=(user)=>user?.app_metadata?.role==='admin';
  const relativeTime=(date)=>{const delta=Date.now()-new Date(date).getTime();const mins=Math.max(1,Math.round(delta/60000));if(mins<60)return `${mins}m ago`;const hours=Math.round(mins/60);if(hours<24)return `${hours}h ago`;const days=Math.round(hours/24);return `${days}d ago`};
  async function sendRecoveryEmail(email,redirectTo){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${cfg.url}/auth/v1/recover?redirect_to=${encodeURIComponent(redirectTo)}`,{method:'POST',headers:{apikey:cfg.publishableKey,Authorization:`Bearer ${cfg.publishableKey}`,'Content-Type':'application/json'},body:JSON.stringify({email}),signal:controller.signal});let payload={};try{payload=await response.json()}catch(_error){}if(!response.ok)throw new Error(payload.msg||payload.message||payload.error_description||`Supabase returned ${response.status}.`)}catch(error){if(error.name==='AbortError')throw new Error('Supabase did not respond within 12 seconds. Check your internet connection and try again.');throw error}finally{clearTimeout(timer)}}

  function setSaveState(message,tone='ready'){$('#saveState span').textContent=message;$('#saveState i').className=tone==='saving'?'ri-loader-4-line':tone==='dirty'?'ri-edit-circle-line':'ri-checkbox-circle-line';}
  function updateCounts(){const text=[form.elements.title.value,form.elements.excerpt.value,form.elements.body_html.value].join(' ').trim();const words=text?text.split(/\s+/).length:0;$('#wordCount').textContent=`${words} ${words===1?'word':'words'}`;$('#characterCount').textContent=`${text.length.toLocaleString()} characters`;$('#readingTime').textContent=`${Math.max(1,Math.ceil(words/220))} min read`;}
  function autoGrow(element){element.style.height='auto';element.style.height=`${Math.max(element.scrollHeight,element===form.elements.title?58:70)}px`;}
  function updateChrome(){const type=form.elements.type.value;const title=form.elements.title.value.trim()||`New ${type==='blog'?'post':'project'}`;$('#breadcrumbType').textContent=type==='blog'?'Blog posts':'Projects';$('#breadcrumbTitle').textContent=title;$('#publishButton').textContent=form.elements.status.value==='published'?'Update':'Publish';$('#statusHelp').textContent=form.elements.status.value==='published'?'This content is visible to the public.':'Drafts are not visible to the public.';}
  function installEditorImageUploads(){const bodyLabel=document.querySelector('label[for="contentBody"]');if(!bodyLabel||$('#editorImageUploads'))return;const panel=document.createElement('section');panel.id='editorImageUploads';panel.className='editor-image-uploads';panel.setAttribute('aria-label','Blog cover image');panel.innerHTML=`<div class="editor-image-card"><div class="editor-image-preview" id="coverImagePreview"><i class="ri-image-add-line"></i></div><div><strong>Blog cover image</strong><p>Used as the homepage thumbnail and the article’s main image.</p><label class="button button-secondary image-upload-button">Choose image<input id="coverImageFile" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><span class="image-upload-status" id="coverImageStatus">JPG, PNG, WebP or GIF · max 2 MB</span></div></div>`;bodyLabel.before(panel);$('#coverImageFile').addEventListener('change',(event)=>uploadEditorImage(event.target.files[0]));const legacyHelp=document.querySelector('.upload-drop span');if(legacyHelp)legacyHelp.textContent='Images max 2 MB · video or PDF max 15 MB';refreshCoverPreview()}
  function refreshCoverPreview(){const preview=$('#coverImagePreview');if(!preview)return;const url=form.elements.cover_url.value.trim();preview.innerHTML=url?`<img src="${escapeText(url)}" alt="Cover image preview">`:'<i class="ri-image-add-line"></i>';const image=preview.querySelector('img');if(image)image.addEventListener('error',()=>{preview.innerHTML='<i class="ri-image-add-line"></i>'},{once:true})}
  async function uploadSmallFile(file,path,onProgress){const {data:{session:active}}=await client.auth.getSession();if(!active)throw new Error('Your session expired. Sign in again.');const objectPath=path.split('/').map(encodeURIComponent).join('/');await new Promise((resolve,reject)=>{const request=new XMLHttpRequest();request.open('POST',`${cfg.url}/storage/v1/object/${encodeURIComponent(cfg.mediaBucket)}/${objectPath}`);request.timeout=25000;request.setRequestHeader('Authorization',`Bearer ${active.access_token}`);request.setRequestHeader('apikey',cfg.publishableKey);request.setRequestHeader('Content-Type',file.type||'application/octet-stream');request.setRequestHeader('x-upsert','false');request.setRequestHeader('cache-control','3600');request.upload.onprogress=(event)=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100))};request.onerror=()=>reject(new Error('The browser could not connect to Supabase Storage. Disable strict tracking protection for this local page and try again.'));request.ontimeout=()=>reject(new Error('The image upload timed out. Check your connection and try again.'));request.onload=()=>{let payload={};try{payload=JSON.parse(request.responseText||'{}')}catch(_error){}if(request.status>=200&&request.status<300)resolve(payload);else reject(new Error(payload.message||payload.error||`Upload failed with status ${request.status}.`))};request.send(file)})}
  async function uploadEditorImage(file){const input=$('#coverImageFile');const message=$('#coverImageStatus');if(!file)return;if(!file.type.startsWith('image/')){status(message,'Choose an image file.',true);input.value='';return}if(file.size>2*1024*1024){status(message,'This image is larger than 2 MB. Compress it and try again.',true);input.value='';return}status(message,'Uploading 0%…');input.disabled=true;const extension=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`images/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${slugify(file.name.replace(/\.[^.]+$/,''))}.${extension}`;try{await uploadSmallFile(file,path,(percent)=>status(message,`Uploading ${percent}%…`));const {data}=client.storage.from(cfg.mediaBucket).getPublicUrl(path);form.elements.cover_url.value=data.publicUrl;refreshCoverPreview();markDirty();status(message,'Cover uploaded. Save or publish to keep it.')}catch(error){console.error('Cover upload failed.',error);status(message,error.message||'Image upload failed.',true)}finally{input.disabled=false;input.value=''}}

  async function boot(){
    if(!client){status($('#loginStatus'),'Add a valid database connection in assets/js/supabase-config.js.',true);return}
    const authError=new URLSearchParams(location.hash.slice(1)).get('error_description');
    if(authError)status($('#loginStatus'),decodeURIComponent(authError.replace(/\+/g,' ')),true);
    client.auth.onAuthStateChange((event,next)=>{session=next;if(event==='PASSWORD_RECOVERY')openNewPasswordDialog();renderSession()});
    const {data}=await client.auth.getSession();session=data.session;renderSession();
    if(session&&new URLSearchParams(location.search).get('reset')==='1')openNewPasswordDialog();
  }
  function openNewPasswordDialog(){const dialog=$('#newPasswordDialog');if(!dialog.open)dialog.showModal();setTimeout(()=>dialog.querySelector('input').focus(),0)}
  function renderSession(){const authed=Boolean(session&&isAdmin(session.user));$('#loginPanel').hidden=authed;$('#studio').hidden=!authed;$('#sessionEmail').textContent=authed?session.user.email:'';if(session&&!authed){status($('#loginStatus'),'This account does not have permission to manage content.',true);client.auth.signOut()}if(authed)loadItems()}
  async function loadItems(preferredId=activeId){setSaveState('Loading…','saving');const {data,error}=await client.from('content_items').select('*').order('updated_at',{ascending:false});if(error){status($('#editorStatus'),error.message,true);setSaveState('Could not load','dirty');return}items=data||[];renderList();if(preferredId&&items.some((item)=>item.id===preferredId))editItem(preferredId,false);else if(!activeId)newItem(false);setSaveState('All changes saved')}
  function renderList(){const term=search.toLowerCase();const visible=items.filter((item)=>(filter==='all'||item.type===filter)&&(!term||`${item.title} ${item.excerpt} ${(item.tags||[]).join(' ')}`.toLowerCase().includes(term)));$('#contentCount').textContent=`${visible.length} ${visible.length===1?'item':'items'}`;$('#contentList').innerHTML=visible.length?visible.map((item)=>`<button class="content-item ${activeId===item.id?'is-active':''}" data-id="${item.id}"><i class="${item.type==='blog'?'ri-file-text-line':'ri-folder-line'}"></i><span><strong>${escapeText(item.title)}</strong><span class="${item.status}">${item.status==='published'?'Published':'Draft'} · ${relativeTime(item.updated_at)}</span></span></button>`).join(''):'<p class="field-help">No matching content.</p>'}
  function newItem(focus=true){activeId='';form.reset();form.elements.id.value='';form.elements.type.value='blog';form.elements.status.value='draft';form.elements.sort_order.value='100';$('#deleteButton').hidden=true;status($('#editorStatus'),'');dirty=false;clearTimeout(saveTimer);localStorage.removeItem('cms-new-draft');updateCounts();updateChrome();refreshCoverPreview();renderList();['title','excerpt'].forEach((name)=>autoGrow(form.elements[name]));if(focus)form.elements.title.focus();closeMobilePanels()}
  function editItem(id,scroll=true){const item=items.find((entry)=>entry.id===id);if(!item)return;activeId=id;Object.entries(item).forEach(([key,value])=>{const field=form.elements[key];if(!field)return;if(field.type==='checkbox')field.checked=Boolean(value);else if(key==='tags')field.value=(value||[]).join(', ');else field.value=value??''});$('#deleteButton').hidden=false;dirty=false;updateCounts();updateChrome();refreshCoverPreview();renderList();['title','excerpt'].forEach((name)=>autoGrow(form.elements[name]));if(scroll)document.querySelector('.editor-canvas').scrollTo({top:0,behavior:'smooth'});closeMobilePanels()}
  function markDirty(){dirty=true;setSaveState('Unsaved changes','dirty');updateCounts();updateChrome();clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(!activeId)localStorage.setItem('cms-new-draft',JSON.stringify(Object.fromEntries(new FormData(form))));setSaveState(activeId?'Unsaved changes':'Draft saved locally','dirty')},700)}
  async function save(event){event?.preventDefault();if(!form.reportValidity())return;setSaveState('Saving…','saving');const values=Object.fromEntries(new FormData(form));const id=values.id;delete values.id;values.title=values.title.trim();values.slug=slugify(values.slug||values.title);values.tags=String(values.tags||'').split(',').map((tag)=>tag.trim()).filter(Boolean);values.featured=form.elements.featured.checked;values.sort_order=Number(values.sort_order)||100;values.author_id=session.user.id;values.updated_at=new Date().toISOString();values.published_at=values.status==='published'?(items.find((item)=>item.id===id)?.published_at||new Date().toISOString()):null;const query=id?client.from('content_items').update(values).eq('id',id).select('id').single():client.from('content_items').insert(values).select('id').single();const {data,error}=await query;if(error){status($('#editorStatus'),error.message,true);setSaveState('Save failed','dirty');return}activeId=data.id;dirty=false;localStorage.removeItem('cms-new-draft');status($('#editorStatus'),values.status==='published'?'Published successfully.':'Draft saved.');setSaveState('All changes saved');await loadItems(activeId)}
  async function publish(){form.elements.status.value='published';updateChrome();await save()}
  async function remove(){if(!activeId||!confirm('Permanently delete this content item? Uploaded media will remain in the media library.'))return;const {error}=await client.from('content_items').delete().eq('id',activeId);if(error){status($('#editorStatus'),error.message,true);return}activeId='';newItem(false);await loadItems()}
  function preview(){const title=escapeText(form.elements.title.value||'Untitled content');const excerpt=escapeText(form.elements.excerpt.value||'');const cover=form.elements.cover_url.value;const video=form.elements.video_url.value;$('#previewContent').innerHTML=`<h1>${title}</h1>${excerpt?`<p class="preview-deck">${excerpt}</p>`:''}${cover?`<img src="${escapeText(cover)}" alt="">`:''}${video?`<video src="${escapeText(video)}" controls></video>`:''}<div>${form.elements.body_html.value||'<p>No body content yet.</p>'}</div>`;$('#previewDialog').showModal()}
  async function upload(){const file=$('#mediaFile').files[0];if(!file)return status($('#uploadStatus'),'Choose a file first.',true);if(file.type.startsWith('image/')&&file.size>2*1024*1024)return status($('#uploadStatus'),'Images must be 2 MB or smaller.',true);if(file.size>15*1024*1024)return status($('#uploadStatus'),'Videos and files must be 15 MB or smaller.',true);const target=$('#mediaTarget').value;const button=$('#uploadButton');const progress=$('#uploadProgress');button.disabled=true;progress.hidden=false;progress.value=0;const extension=(file.name.split('.').pop()||'file').toLowerCase();const path=`${form.elements.type.value}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${slugify(file.name.replace(/\.[^.]+$/,''))}.${extension}`;try{if(file.size>6*1024*1024)await resumableUpload(file,path,(percent)=>{progress.value=percent;status($('#uploadStatus'),`Uploading ${percent}%…`)});else{const {error}=await client.storage.from(cfg.mediaBucket).upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;progress.value=100}const {data}=client.storage.from(cfg.mediaBucket).getPublicUrl(path);form.elements[target].value=data.publicUrl;if(target==='cover_url')refreshCoverPreview();markDirty();status($('#uploadStatus'),'Upload complete. Save or publish to keep this media URL.')}catch(error){status($('#uploadStatus'),error.message||'Upload failed.',true)}finally{button.disabled=false}}
  async function resumableUpload(file,path,onProgress){const {data:{session:active}}=await client.auth.getSession();if(!active)throw new Error('Your session expired. Sign in again.');const projectRef=new URL(cfg.url).hostname.split('.')[0];await new Promise((resolve,reject)=>{new tus.Upload(file,{endpoint:`https://${projectRef}.storage.supabase.co/storage/v1/upload/resumable`,retryDelays:[0,1000,3000,5000],headers:{authorization:`Bearer ${active.access_token}`,apikey:cfg.publishableKey,'x-upsert':'false'},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,metadata:{bucketName:cfg.mediaBucket,objectName:path,contentType:file.type,cacheControl:'3600'},chunkSize:6*1024*1024,onError:reject,onProgress:(sent,total)=>onProgress(Math.round(sent/total*100)),onSuccess:resolve}).start()})}
  function closeMobilePanels(){$('#contentDrawer').classList.remove('is-open');$('#inspector').classList.remove('is-open')}
  function insertSnippet(snippet){const field=form.elements.body_html;const start=field.selectionStart;field.setRangeText(snippet,start,field.selectionEnd,'end');field.focus();markDirty()}
  function installEngagementTools(){const bar=$('.format-bar');if(!bar||bar.querySelector('[data-engagement-tool]'))return;const divider=document.createElement('span');divider.className='format-divider';bar.append(divider);[{label:'Key takeaway',icon:'ri-lightbulb-line',snippet:'<aside class="post-callout"><strong>Key takeaway</strong><p>Add the most useful point here.</p></aside>'},{label:'CTA button',icon:'ri-cursor-line',snippet:'<div class="post-cta"><p>Ready to take the next step?</p><a class="cta-button" href="https://">Call to action</a></div>'}].forEach((tool)=>{const button=document.createElement('button');button.type='button';button.title=tool.label;button.setAttribute('aria-label',tool.label);button.dataset.engagementTool='';button.dataset.insert=tool.snippet;button.innerHTML=`<i class="${tool.icon}"></i>`;bar.append(button)})}

  installEngagementTools();
  $('#loginForm').addEventListener('submit',async(event)=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;status($('#loginStatus'),'Signing in…');const values=Object.fromEntries(new FormData(event.target));const {error}=await client.auth.signInWithPassword(values);button.disabled=false;if(error)status($('#loginStatus'),error.message,true)});
  $('#forgotPasswordButton').addEventListener('click',()=>$('#recoveryDialog').showModal());
  $('#closeRecovery').addEventListener('click',()=>$('#recoveryDialog').close());
  $('#recoveryForm').addEventListener('submit',async(event)=>{event.preventDefault();const button=event.target.querySelector('button[type="submit"]');const email=String(new FormData(event.target).get('email')||'').trim();button.disabled=true;status($('#recoveryStatus'),'Sending a fresh link…');try{const redirectTo=/^https?:$/.test(location.protocol)?new URL('./?reset=1',location.href).href:'http://127.0.0.1:4182/admin/?reset=1';await sendRecoveryEmail(email,redirectTo);status($('#recoveryStatus'),'Recovery email sent. Use only the newest link; older links will no longer work.')}catch(error){status($('#recoveryStatus'),error.message||'The recovery email could not be sent.',true)}finally{button.disabled=false}});
  $('#newPasswordForm').addEventListener('submit',async(event)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));if(values.password!==values.confirm_password)return status($('#newPasswordStatus'),'The passwords do not match.',true);const button=event.target.querySelector('button[type="submit"]');button.disabled=true;status($('#newPasswordStatus'),'Updating password…');const {error}=await client.auth.updateUser({password:values.password});button.disabled=false;if(error)return status($('#newPasswordStatus'),error.message,true);status($('#newPasswordStatus'),'Password updated. You are signed in.');history.replaceState({},'',location.pathname);setTimeout(()=>{$('#newPasswordDialog').close();renderSession()},700)});
  form.addEventListener('submit',save);form.addEventListener('input',(event)=>{if(event.target.matches('input,textarea,select')){if(event.target===form.elements.title&&!activeId)form.elements.slug.value=slugify(event.target.value);if(event.target===form.elements.cover_url)refreshCoverPreview();if(event.target.matches('.title-input,.deck-input'))autoGrow(event.target);markDirty()}});form.addEventListener('change',markDirty);
  $('#contentSearch').addEventListener('input',(event)=>{search=event.target.value;renderList()});$('#contentList').addEventListener('click',(event)=>{const button=event.target.closest('[data-id]');if(button){if(dirty&&!confirm('Discard unsaved changes and open another item?'))return;editItem(button.dataset.id)}});
  $$('#newItemButton,#newItemFooter').forEach((button)=>button.addEventListener('click',()=>{if(!dirty||confirm('Discard unsaved changes and create new content?'))newItem()}));$$('[data-filter]').forEach((button)=>button.addEventListener('click',()=>{filter=button.dataset.filter;$$('[data-filter]').forEach((item)=>item.classList.toggle('is-active',item===button));renderList()}));$$('[data-insert]').forEach((button)=>button.addEventListener('click',()=>insertSnippet(button.dataset.insert)));
  $('#publishButton').addEventListener('click',publish);$('#previewButton').addEventListener('click',preview);$('#closePreview').addEventListener('click',()=>$('#previewDialog').close());$('#deleteButton').addEventListener('click',remove);$('#uploadButton').addEventListener('click',upload);$('#signOutButton').addEventListener('click',()=>client.auth.signOut());$('#accountButton').addEventListener('click',()=>{const menu=$('#accountMenu');menu.hidden=!menu.hidden;$('#accountButton').setAttribute('aria-expanded',String(!menu.hidden))});$('#allContentButton').addEventListener('click',()=>{$('#contentDrawer').classList.add('is-open')});$('#drawerButton').addEventListener('click',()=>$('#contentDrawer').classList.toggle('is-open'));$('#inspectorButton').addEventListener('click',()=>$('#inspector').classList.add('is-open'));$('#closeInspector').addEventListener('click',()=>$('#inspector').classList.remove('is-open'));
  document.addEventListener('keydown',(event)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save()}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();$('#contentDrawer').classList.add('is-open');$('#contentSearch').focus()}});window.addEventListener('beforeunload',(event)=>{if(dirty){event.preventDefault();event.returnValue=''}});
  installEditorImageUploads();boot();
})();
